//
//  UIKit.swift
//  GENERATED by preview-swiftui. Edit freely; it will not be rewritten.
//
//  This exists so `import UIKit` resolves. The UIKit types themselves
//  ship with the engine and are already visible in every file, so
//  there is deliberately nothing here to duplicate them: a second
//  UIScreen or UIColor gives the compiler two of each and produces
//  errors that name neither.
//
//  AppModel.swift is what asked for UIKit here.
//
//  WHAT IS REAL: the shape, and state that reads back what was written.
//  A `UIViewRepresentable` runs its `makeUIView` and `updateUIView`, so
//  the app's own setup executes; a view holding text draws that text.
//
//  WHAT IS NOT: anything reaching a system. Feedback generators do
//  nothing. `UIApplication.shared.open` returns false. `UIScreen` and
//  `UIDevice` report a plausible phone, not this machine.
//
//  TO ADD WHAT YOUR APP NEEDS, put it here: an extension on a shipped
//  type, or a type the engine does not carry. To change a shipped one,
//  subclass it - they are open. This file is yours; the engine will not
//  touch it again.
//

// Re-exported, because that is what UIKit does on a phone: a file that
// says `import UIKit` and nothing else still sees CGFloat, CGRect and
// NSObject. Plain imports here left those invisible, and the compiler
// said "cannot find type 'CGFloat' in scope; did you mean to use
// 'CGFloat'?", which is what it says when a type exists but arrived
// through an import that does not carry it onward.
@_exported import Foundation
@_exported import MobAIPreviewFoundation

// ImageIO rides along too, because that is what UIKit does on a
// phone: CGImageSourceCreateWithURL in a file that imports UIKit
// alone is normal app code. On this machine the real framework
// decodes for real; on Linux the guard leaves this out.
#if canImport(ImageIO)
  @_exported import ImageIO
#endif

// Observation rides along as well: a phone's UIKit reaches it through
// Foundation, and files like a SceneDelegate use @Observable with only
// `import UIKit` at the top. The SwiftUI shim exports the same module,
// so a file importing both sees one Observation, not two.
@_exported import Observation
#if canImport(AppKit)
// The REAL attachment type: Foundation's attributed-string APIs on
// this host take AppKit's, and a twin was unconvertible to it.
import AppKit
public typealias NSTextAttachment = AppKit.NSTextAttachment
#else
// Linux has no AppKit and Foundation's attributed strings there take
// no attachment type at all; a bare twin keeps the name compiling.
open class NSTextAttachment: NSObject {
    open var image: UIImage?
    open var bounds: CGRect = .zero
    public override init() { super.init() }
    public init(image: UIImage) { self.image = image; super.init() }
}
#endif
